//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelApplicationDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendantsList
    {
        public System.Guid Id { get; set; }
        public string AttendantName { get; set; }
        public string EncryptionKey { get; set; }
        public string Shortcode { get; set; }
        public string Status { get; set; }
    }
}
