//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelApplicationDashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FuelDBEntities : DbContext
    {
        public FuelDBEntities()
            : base("name=FuelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TXN> TXNs { get; set; }
        public virtual DbSet<AttendantsList> AttendantsLists { get; set; }
        public virtual DbSet<FuelPrice> FuelPrices { get; set; }
        public virtual DbSet<FuleOTP> FuleOTPs { get; set; }
        public virtual DbSet<MerchantInfo> MerchantInfoes { get; set; }
    }
}
