//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuelApplicationDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantInfo
    {
        public long Id { get; set; }
        public string Shortcode { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string KYC { get; set; }
        public string Status { get; set; }
        public System.DateTime InsertDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string InsertUser { get; set; }
        public string UpdateUser { get; set; }
    }
}
